import { getEnv } from "@/utils/get-env.js";

export const env = {
  NODE_ENV: getEnv("NODE_ENV"),

  PORT: Number(getEnv("PORT")),

  MONGO_URI: getEnv("MONGO_URI"),

  FRONTEND_URL_DEV: getEnv("FRONTEND_URL_DEV"),
  FRONTEND_URL_PROD: getEnv("FRONTEND_URL_PROD"),

  JWT_ACCESS_SECRET: getEnv("JWT_ACCESS_SECRET"),
  JWT_ACCESS_EXPIRE: Number(getEnv("JWT_ACCESS_EXPIRE")),
  JWT_REFRESH_SECRET: getEnv("JWT_REFRESH_SECRET"),
  JWT_REFRESH_EXPIRE: Number(getEnv("JWT_REFRESH_EXPIRE")),

  GOOGLE_CLIENT_ID: getEnv("GOOGLE_CLIENT_ID"),
  GOOGLE_CLIENT_SECRET: getEnv("GOOGLE_CLIENT_SECRET"),

  CLOUDINARY_CLOUD_NAME: getEnv("CLOUDINARY_CLOUD_NAME"),
  CLOUDINARY_API_KEY: getEnv("CLOUDINARY_API_KEY"),
  CLOUDINARY_API_SECRET: getEnv("CLOUDINARY_API_SECRET"),
};
